################################################################################
# Appveyor-CI
# -----------
#
################################################################################

# Setup
################################################################################

version: "{build}"

branches:
  except:
    - prototype/.*
    - gh-pages

# Agents
################################################################################

os:
  - Visual Studio 2017

# Jobs
################################################################################

- platform:
  - Win32
  - x64

- configuration:
  - Debug
  - Release

# Stages
################################################################################

before_build:
  - set CXXFLAGS="/permissive- /std:c++latest"
  - cmd: .\.appveyor\before-build.cmd

build:
  project: build\Alloy.sln
  parallel: true
  verbosity: normal

test_script:
  - cmd: .\.appveyor\test.cmd