var hierarchy =
[
    [ "alloy::core::basic_angle< AngleUnit >", "d7/d2e/classalloy_1_1core_1_1basic__angle.html", null ],
    [ "alloy::core::basic_angle< radian_unit >", "d7/d2e/classalloy_1_1core_1_1basic__angle.html", null ],
    [ "alloy::core::basic_angle_constants< AngleUnit >", "db/d1f/structalloy_1_1core_1_1basic__angle__constants.html", null ],
    [ "alloy::core::basic_fixed< MantissaBits, ExponentBits >", "d7/db1/classalloy_1_1core_1_1basic__fixed.html", null ],
    [ "alloy::core::basis2", "d4/d54/classalloy_1_1core_1_1basis2.html", null ],
    [ "alloy::core::basis3", "dd/d90/classalloy_1_1core_1_1basis3.html", null ],
    [ "alloy::core::color", "d0/d22/classalloy_1_1core_1_1color.html", null ],
    [ "alloy::core::degree_unit", "d8/d65/structalloy_1_1core_1_1degree__unit.html", null ],
    [ "alloy::core::euler_angles", "d9/dce/classalloy_1_1core_1_1euler__angles.html", null ],
    [ "false_type", null, [
      [ "alloy::core::is_angle< T >", "dd/d5f/structalloy_1_1core_1_1is__angle.html", null ],
      [ "alloy::core::is_degree< T >", "d9/d94/structalloy_1_1core_1_1is__degree.html", null ],
      [ "alloy::core::is_gradian< T >", "dd/de0/structalloy_1_1core_1_1is__gradian.html", null ],
      [ "alloy::core::is_matrix< T >", "d6/d1e/structalloy_1_1core_1_1is__matrix.html", null ],
      [ "alloy::core::is_matrix2< T >", "da/dde/structalloy_1_1core_1_1is__matrix2.html", null ],
      [ "alloy::core::is_matrix3< T >", "d4/dfa/structalloy_1_1core_1_1is__matrix3.html", null ],
      [ "alloy::core::is_matrix4< T >", "d9/d1b/structalloy_1_1core_1_1is__matrix4.html", null ],
      [ "alloy::core::is_quaternion< T >", "d2/d9e/structalloy_1_1core_1_1is__quaternion.html", null ],
      [ "alloy::core::is_radian< T >", "d0/d5e/structalloy_1_1core_1_1is__radian.html", null ],
      [ "alloy::core::is_vector< T >", "d8/da2/structalloy_1_1core_1_1is__vector.html", null ],
      [ "alloy::core::is_vector2< T >", "db/d9b/structalloy_1_1core_1_1is__vector2.html", null ],
      [ "alloy::core::is_vector3< T >", "d6/d52/structalloy_1_1core_1_1is__vector3.html", null ],
      [ "alloy::core::is_vector4< T >", "dd/dd6/structalloy_1_1core_1_1is__vector4.html", null ]
    ] ],
    [ "alloy::core::gradian_unit", "df/d9a/structalloy_1_1core_1_1gradian__unit.html", null ],
    [ "alloy::core::hsb", "de/dd5/structalloy_1_1core_1_1hsb.html", null ],
    [ "alloy::core::interpolation", "db/d92/structalloy_1_1core_1_1interpolation.html", null ],
    [ "alloy::core::line_segment", "d3/d3a/classalloy_1_1core_1_1line__segment.html", null ],
    [ "alloy::core::math_constants", "d1/d75/structalloy_1_1core_1_1math__constants.html", null ],
    [ "alloy::core::matrix2", "d4/d89/classalloy_1_1core_1_1matrix2.html", null ],
    [ "alloy::core::matrix2_constants", "da/d5b/structalloy_1_1core_1_1matrix2__constants.html", null ],
    [ "alloy::core::matrix3", "d6/dbc/classalloy_1_1core_1_1matrix3.html", null ],
    [ "alloy::core::matrix3_constants", "d6/d31/structalloy_1_1core_1_1matrix3__constants.html", null ],
    [ "alloy::core::matrix4", "df/da7/classalloy_1_1core_1_1matrix4.html", null ],
    [ "alloy::core::matrix4_constants", "d4/d8a/structalloy_1_1core_1_1matrix4__constants.html", null ],
    [ "alloy::core::piecewise_compare< T >", "d1/d93/structalloy_1_1core_1_1piecewise__compare.html", null ],
    [ "alloy::core::piecewise_compare< point >", "db/d2c/structalloy_1_1core_1_1piecewise__compare_3_01point_01_4.html", null ],
    [ "alloy::core::piecewise_compare< vector2 >", "d1/df7/structalloy_1_1core_1_1piecewise__compare_3_01vector2_01_4.html", null ],
    [ "alloy::core::piecewise_compare< vector3 >", "db/d64/structalloy_1_1core_1_1piecewise__compare_3_01vector3_01_4.html", null ],
    [ "alloy::core::piecewise_compare< vector4 >", "de/d14/structalloy_1_1core_1_1piecewise__compare_3_01vector4_01_4.html", null ],
    [ "alloy::core::plane", "d1/d99/classalloy_1_1core_1_1plane.html", null ],
    [ "alloy::core::point", "d3/da9/classalloy_1_1core_1_1point.html", null ],
    [ "alloy::core::quaternion_constants", "db/d94/structalloy_1_1core_1_1quaternion__constants.html", null ],
    [ "alloy::core::radian_unit", "d8/d9b/structalloy_1_1core_1_1radian__unit.html", null ],
    [ "alloy::core::ray", "d1/dea/classalloy_1_1core_1_1ray.html", null ],
    [ "alloy::core::simplex", "dc/d90/structalloy_1_1core_1_1simplex.html", null ],
    [ "alloy::core::sphere", "d5/d2f/classalloy_1_1core_1_1sphere.html", null ],
    [ "alloy::core::trigonometry", "d7/d1b/structalloy_1_1core_1_1trigonometry.html", null ],
    [ "true_type", null, [
      [ "alloy::core::is_angle< basic_angle< AngleUnit > >", "dc/d5f/structalloy_1_1core_1_1is__angle_3_01basic__angle_3_01_angle_unit_01_4_01_4.html", null ],
      [ "alloy::core::is_degree< degree >", "d5/dfc/structalloy_1_1core_1_1is__degree_3_01degree_01_4.html", null ],
      [ "alloy::core::is_gradian< gradian >", "d3/d9e/structalloy_1_1core_1_1is__gradian_3_01gradian_01_4.html", null ],
      [ "alloy::core::is_matrix2< matrix2 >", "da/d45/structalloy_1_1core_1_1is__matrix2_3_01matrix2_01_4.html", null ],
      [ "alloy::core::is_matrix3< matrix3 >", "d2/d5f/structalloy_1_1core_1_1is__matrix3_3_01matrix3_01_4.html", null ],
      [ "alloy::core::is_matrix4< matrix4 >", "d5/deb/structalloy_1_1core_1_1is__matrix4_3_01matrix4_01_4.html", null ],
      [ "alloy::core::is_matrix< matrix2 >", "dc/dfa/structalloy_1_1core_1_1is__matrix_3_01matrix2_01_4.html", null ],
      [ "alloy::core::is_matrix< matrix3 >", "dd/dc5/structalloy_1_1core_1_1is__matrix_3_01matrix3_01_4.html", null ],
      [ "alloy::core::is_matrix< matrix4 >", "d9/dd1/structalloy_1_1core_1_1is__matrix_3_01matrix4_01_4.html", null ],
      [ "alloy::core::is_quaternion< quaternion >", "da/d05/structalloy_1_1core_1_1is__quaternion_3_01quaternion_01_4.html", null ],
      [ "alloy::core::is_radian< radian >", "d6/dd4/structalloy_1_1core_1_1is__radian_3_01radian_01_4.html", null ],
      [ "alloy::core::is_vector2< vector2 >", "de/dbd/structalloy_1_1core_1_1is__vector2_3_01vector2_01_4.html", null ],
      [ "alloy::core::is_vector3< vector3 >", "da/dbf/structalloy_1_1core_1_1is__vector3_3_01vector3_01_4.html", null ],
      [ "alloy::core::is_vector4< vector4 >", "d2/dde/structalloy_1_1core_1_1is__vector4_3_01vector4_01_4.html", null ],
      [ "alloy::core::is_vector< vector2 >", "dc/d6c/structalloy_1_1core_1_1is__vector_3_01vector2_01_4.html", null ],
      [ "alloy::core::is_vector< vector3 >", "da/dd5/structalloy_1_1core_1_1is__vector_3_01vector3_01_4.html", null ],
      [ "alloy::core::is_vector< vector4 >", "dd/da7/structalloy_1_1core_1_1is__vector_3_01vector4_01_4.html", null ]
    ] ],
    [ "alloy::core::vector2", "dc/dcf/classalloy_1_1core_1_1vector2.html", null ],
    [ "alloy::core::vector2_constants", "d7/d9e/structalloy_1_1core_1_1vector2__constants.html", null ],
    [ "alloy::core::vector3", "d3/ded/classalloy_1_1core_1_1vector3.html", null ],
    [ "alloy::core::vector3_constants", "d0/ded/structalloy_1_1core_1_1vector3__constants.html", null ],
    [ "alloy::core::vector4", "dc/d54/classalloy_1_1core_1_1vector4.html", null ],
    [ "alloy::core::vector4_constants", "d3/d5a/structalloy_1_1core_1_1vector4__constants.html", null ],
    [ "alloy::core::vector_traits< T >", "d2/d0a/structalloy_1_1core_1_1vector__traits.html", null ]
];